<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>Justin King</Authors>
    <Company>Wheelhouse</Company>
    <Copyright>Copyright © 2026 Justin King</Copyright>
    <RepositoryUrl>https://github.com/justinswork/Wheelhouse</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
