<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
<StartupObject>Wheelhouse.UI.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator></Generator>
      <LastGenOutput></LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.fr.resx">
      <Generator></Generator>
      <LastGenOutput></LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wheelhouse.Core\Wheelhouse.Core.csproj" />
    <ProjectReference Include="..\Wheelhouse.Hosting.Abstractions\Wheelhouse.Hosting.Abstractions.csproj" />
    <ProjectReference Include="..\Wheelhouse.Hosting.GitHub\Wheelhouse.Hosting.GitHub.csproj" />
    <ProjectReference Include="..\Wheelhouse.Hosting.AzureDevOps\Wheelhouse.Hosting.AzureDevOps.csproj" />
    <ProjectReference Include="..\Wheelhouse.Terminal\Wheelhouse.Terminal.csproj" />
  </ItemGroup>

</Project>
